serviceAccount:
  create: true
  name: fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_FLUENT_BIT_ROLE_ARN
env:
  - name: AWS_REGION
    value: REPLACE_WITH_AWS_REGION
  - name: AWS_STS_REGIONAL_ENDPOINTS
    value: regional
resources:
  requests: { cpu: 25m, memory: 64Mi }
  limits: { cpu: 100m, memory: 128Mi }
config:
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
  outputs: |
    [OUTPUT]
        Name s3
        Match kube.*
        bucket REPLACE_WITH_LOGS_BUCKET_NAME
        region REPLACE_WITH_AWS_REGION
        total_file_size 10M
        upload_timeout 1m
        store_dir /tmp/fluent-bit/s3
        store_dir_limit_size 100M
        use_put_object On
        s3_key_format /kubernetes/$TAG/%Y/%m/%d/%H/%M/%S-$UUID.gz
