apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/vipinkumar1234/aws-eks-production-platform.git"
    - "https://aws.github.io/eks-charts"
    - "https://charts.karpenter.sh"
    - "https://charts.jetstack.io"
    - "https://kubernetes-sigs.github.io/metrics-server/"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://fluent.github.io/helm-charts"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
