apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.0
    helm:
      valueFiles:
      - $values/gitops/platform/aws-load-balancer-controller/values.yaml
  - repoURL: https://github.com/vipinkumar1234/aws-eks-production-platform.git
    targetRevision: main
    ref: values
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.0
    helm:
      valueFiles:
      - $values/gitops/platform/metrics-server/values.yaml
  - repoURL: https://github.com/vipinkumar1234/aws-eks-production-platform.git
    targetRevision: main
    ref: values

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-resources
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/vipinkumar1234/aws-eks-production-platform.git
    targetRevision: main
    path: gitops/platform/karpenter-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
