clusterName: REPLACE_WITH_TERRAFORM_CLUSTER_NAME
region: REPLACE_WITH_AWS_REGION
vpcId: REPLACE_WITH_TERRAFORM_VPC_ID
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_ALB_CONTROLLER_ROLE_ARN
