apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
  - repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.48.9
    helm:
      valueFiles:
      - $values/gitops/observability/fluent-bit/values.yaml
  - repoURL: https://github.com/vipinkumar1234/aws-eks-production-platform.git
    targetRevision: main
    ref: values
